### ISSUE TITLE
Use recent-ish ffmpeg improved gif output

### ISSUE THREAD

**Issue by EphramPerdition** [Malabarba/camcorder.el#5]
I just used camcorder.el for the first time and although getting a gif was as easy as picking a fight with the hulk, the output quality with ffmpeg was quite bad with dithering artifcats.

a search uncovered he fact that ffmpeg landed some major improvements to this earlier this year:
http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
https://superuser.com/a/556031

In particular the two-pass solution with a calculated pallete resulted in far better output.

Compare: 
![old](https://cloud.githubusercontent.com/assets/15329740/10805144/54987384-7dd4-11e5-943f-06e56603a566.png)
With: 

![new](https://cloud.githubusercontent.com/assets/15329740/10805146/564c5e02-7dd4-11e5-8beb-5808af63a53f.png)

**Comment by Malabarba** [comment]
Indeed, that looks much nicer. Would you like to  submit a PR with an extra command option?

**Comment by EphramPerdition** [comment]
Sorry, No. I fiddled with things until I got what I wanted but I'd have to experiment a lot more to figure out something that should work for everyone (it doubled the filesize, for one) and I don't want to spend that much time on this. 

So just a helpful pointer for other users experiencing the same issue.

**Comment by Malabarba** [comment]
No problem. Thanks for the pointer.

**Comment by DamienCassou** [comment]
I've used the same process. Here are my commands:

```
$ ffmpeg -i input.ogv -vf palettegen input.palette.png
$ ffmpeg -i input.ogv -i input.palette.png -filter_complex paletteuse input.gif
```

**Comment by jcaw** [comment]
> I've used the same process. Here are my commands:
> 
> ```
> $ ffmpeg -i input.ogv -vf palettegen input.palette.png
> $ ffmpeg -i input.ogv -i input.palette.png -filter_complex paletteuse input.gif
> ```

I've opened a pull request implementing this as the new default command (the original is kept as a fallback in case people want the smaller file size).
