### ISSUE TITLE
Instead of -4, would using outer-window-id work?

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/camcorder.el#6]
On my machine at least, `(frame-parameter nil 'outer-window-id)` seems to give the right value (instead of a vale with a -4 offset).

**Comment by Malabarba** [comment]
If it works for you, that's 1 more person than the current solution. :-)
Would you like to submit a PR with that?

**Comment by cpitclaudel** [comment]
Sure; should I remove the offset setting?

**Comment by Malabarba** [comment]
I think it's best to keep the setting for now, but defaulting to 0.

**Comment by cpitclaudel** [comment]
All set :) Seems to work for me, please test?
